  ip_webcam_settings:
    name: IP Webcam Settings
    entities:
      - sensor.ip_webcam_pressure
      - sensor.ip_webcam_motion
      - sensor.ip_webcam_light_level
      - sensor.ip_webcam_battery_voltage
      - sensor.ip_webcam_battery_temperature
      - sensor.ip_webcam_battery_level
      - sensor.ip_webcam_audio_connections
      - switch.ip_webcam_white_balance_lock
      - switch.ip_webcam_video_recording
      - switch.ip_webcam_torch
      - switch.ip_webcam_overlay
      - switch.ip_webcam_night_vision
      - switch.ip_webcam_gps_active
      - switch.ip_webcam_frontfacing_camera
      - switch.ip_webcam_focus
      - switch.ip_webcam_exposure_lock